# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and LICENSE-assistant contributors
#
# SPDX-License-Identifier: Apache-2.0

# Docker compose file to get an instance of LICENSE-assistant quickly up
# Mainly for development purposes
# NOT PRODUCTION READY
version: '3.7'
services:
  license-assistant:
    image: license-assistant
    build: .
    ports:
      - "5000:5000"
    networks:
      - cla
    env_file:
      - .env
    environment:
      MONGODB: mongodb://license-db:27017/license_assistant
    depends_on:
      - cla-db
  cla-db:
    image: mongo
    networks:
      - cla
networks:
  cla: